---
  - name: Installing and setting up Podman 
    hosts: all
    become: true
    tasks: 
      - name: Sudo apt update
        ansible.builtin.apt:
                update_cache: yes
        when: ansible_distribution in ["Ubuntu", "Debian"]
       - name: upgrade all dnf
           ansible.builtin.dnf:
                 name: "*"
                 state: latest
          when: ansible_distribution in ["Rocky", "Rocky Enterprise Software Foundation"]
        - name: Installing Podman
          ansible.builtin.package:
                name: podman
                state: latest
         - name: Pulling httpd:2-alpine image from dockerhub
           podman_image:
              name: docker.io/httpd
              tag: 2-alpine
         - name: Running the httpd image.
            containers.podman.podman_container:
                  name: container1
                  image:  docker.io/httpd:2-alpine
                  state: started

                                                    
